### ISSUE TITLE
Chrome on Android phone

### ISSUE THREAD

**Issue by GabbyCinco** [tylerhearon/ecommerce-pattern-library#9]
1. The speed of the website is a little slow
2. It took me a bit to figure out how to purchase an item on mobile screen size. There is a button bellow the product cards so it made me think that it was a very large card. I just did not realise that they were all small cards placed together.
<img width="506" alt="Screen Shot 2019-04-15 at 9 32 05 AM" src="https://user-images.githubusercontent.com/31907109/56136876-a23ec580-5f61-11e9-9a26-a95e90eb6358.png">

Overall, the website looks great! Everything seems to be linked properly.

**Comment by tylerhearon** [comment]
Thank you Gabby!  Will consider reorganizing for clarity and condensing some image usage.
